### ISSUE TITLE
Question about access token

### ISSUE THREAD

**Issue by Iakobs** [godot-sdk-integrations/godot-play-game-services#39]
Thank you.. I have it working!!

 but now is it possible to get id_token? !'m sending request to "https://oauth2.googleapis.com/token" and it only gives access_token with the auth_code provided

_Originally posted by @Classified154 in https://github.com/godot-sdk-integrations/godot-play-game-services/issues/31#issuecomment-2428345973_

**Comment by Iakobs** [comment]
Hi @Classified154 I have moved your question here! You mean how to get the access token for the server? Once you call the `SignInClient.request_server_side_access` you have to connect to the `server_side_access_requested` signal,which will sent back the oauth code. Is this what you need?

**Comment by Classified154** [comment]
Thats a part of process, 
After you get auth code, you can request "access_token" from google apis with which you can "ID_token", which wasnt present..

Soooo I googled a bit and found the problem, its related to scopes, google play game services dont allow scope like openid, email, etc when you sign in.. and without these the "Id_token" (which I was asking) wont be provided..

The only way to get those scope now is to have google sign next to google play
More info here
https://developers.google.com/games/services/common/concepts/sign-in

But nothing to worry about Im not going to use id_token anymore, will just make my way with playerID

**Comment by Iakobs** [comment]
Nice! I see what you mean now. That means I can close this issue now. Please let me know if you need anything else!
