### ISSUE TITLE
Cannot submit a score in the LeaderBoard

### ISSUE THREAD

**Issue by Zito93** [godot-sdk-integrations/godot-play-game-services#41]
Hello,
I tried to add a LeaderBoard in my app but I can't submit a score.
I can log in, and display the leaderboard, and I also unlock achivements.
I also tried to use directely the func "LeaderboardsClient.submit_score("xxxxxxxxx", 300)" with the value and the leaderboard ID hardcoded. But it won't work.

In adb logcat, I can't see revealent logs, only "Plugin found!" at launch.

In PlayConsole side, I think I correctly configured the credentials, achivements and the leaderboard.
I also tried everythink in the[ Issue #36](https://github.com/godot-sdk-integrations/godot-play-game-services/issues/36)

Thank you for your help.

**Comment by Iakobs** [comment]
Hi @Zito93 thanks for reaching out! I'm sorry to hear about your problem, unfortunately if you already tried what's described in the issue you mentioned and all the other features of the plugin work fine, this looks like a configuration problem with Google Console.

I know that the Google API only accept scores greater than the last one registered for that player, but maybe there's a type of leaderboard to change that. I remember that the type of leaderboards and what type of scores they accept were a bit complicated, so I'll suggest double checking that.

The other very common issue is that you have to publish your changes in your play games section EVERY time. That was very confusing to me at the beginning.

I'll keep the issue open, let's see if we can figure this out!

**Comment by Zito93** [comment]
Thank you @lakobs for your reply.

The issue was with the privacy settings of my Google account. My score was not shared, which is why it didn’t appear on the leaderboard!

**Comment by Iakobs** [comment]
good to know! thanks for letting me know, so it can help others!
