### ISSUE TITLE
  No plugin found!

### ISSUE THREAD

**Issue by Keyvan-Rostyslav** [godot-sdk-integrations/godot-play-game-services#42]
Got an error when running the demo project in Editor. Godot 4.3
<img width="695" alt="Снимок экрана 2024-11-09 222859" src="https://github.com/user-attachments/assets/17463645-b368-4ff2-8e0e-f58cbd07f516">

**Comment by Iakobs** [comment]
Hi @Keyvan-Rostyslav thanks for reaching out!

I will need more information to help you, did you follow all the steps described in the README? Are you running the project in a device (real or emulated)?

The more details, the easier to figure out what could be the issue 😊

**Comment by Keyvan-Rostyslav** [comment]
My actions:

Created an empty project
Added export templates
Configured Export
Downloaded .zip GooglePlayGameServices
Moved GodotPlayGameServices to folder (addon)
Enabled the plugin in the project settings
Set the Application ID of the services
There are no errors in the console
Run the project in Godot Gives an error "No Plugin Found"
Build on Android 15 (Not an emulator)
Run the project
Nothing works, the inscription "No Plugin Found" is on top

**Comment by Iakobs** [comment]
Hi!

The plugin not working on godot editor is normal, it needs to run on a device, real via wi-fi or usb debugging, or emulated, but as you said it's not working there either. Your steps seem correct to me. Also please check that the package in the export configuration matches the package in the credentials in your Google Cloud.

About the configuration in Google Play Console, your Play Games section of your game is published? If you search the adb logs with this filter: `package:com.google.android.gms` is there anything else beside the game's log `No Plugin Found`?

**Comment by Keyvan-Rostyslav** [comment]
Google Services is configured and published, has the same SHA-1 fingerprints and game name. Do I need to configure export_template permissions to the Wi-Fi device? I'm more referring to the fact that in the _Ready method during initialization, the field ( var android_plugin: Object) cannot get the plugin in the list of singletons, or the process occurs on the side of the plugin, the process of which has not yet started, the initialization of services has already begun.

var plugin_name := "GodotPlayServices"

if not android_plugin:
if Engine.has_singleton(plugin_name):
print("Plugin found!")

android_plugin = Engine.get_singleton(plugin_name)
android_plugin.initialize()
else:
printerr("No plugin found!")

Tell me where I could get these logs?

**Comment by Iakobs** [comment]
I usually use android studio's logcat to see the adb logs of the connected device. You can do it directly with a terminal, but I don't know the command from the top of my head.

**Comment by Keyvan-Rostyslav** [comment]
Thank you very much for your support, I solved the problem, the problem was that the plugins folder (bin) was missing, which I had not moved by mistake. Everything works. Is there a list of all the plugin signals, it would be very helpful for people in development. By the way, I could translate your plugin into C# if there is a need. =)

**Comment by Iakobs** [comment]
I'm glad you solved it! About documenting the signals, that's a great idea!

The kotlin code is documented, though, [here](https://godot.jacobibanez.com/plugin/com.jacobibanez.plugin.android.godotplaygameservices.signals/index.html). The GDScript signals are the same, but in snake case instead of lower camel case.

The GDScript code is also documented inside the godot editor, but I will search for a way of publishing it online too, like godot docs.

I'm closing this issue in the meantime, since your problem was solved. Let me know if you need anything else!
