### ISSUE TITLE
Error enabling the plugin

### ISSUE THREAD

**Issue by manuelarte** [godot-sdk-integrations/godot-play-game-services#46]
Hi,

When trying to add your plugin I got the following error:

![add_autoload_error](https://github.com/user-attachments/assets/218a583d-e485-482e-adce-2835c4beac48)

Steps that I follow:
- Download the addons.zip from the Github Release page (v 2.0.0)
- Unzip the file inside the addons folder, so then the folder structure is the following:
```
/addons
    /GodotPlayGamesService
```

**Comment by Iakobs** [comment]
Hi @manuelarte thanks for using the plugin! I'm sorry you're having this issue. The error is very strange though, do the logs tell anything else about why the scripts are not compiling?

Also, can you try closing and reopening the project? I remember that sometimes the plugin can error on the first load, but then work fine.

I'm also assuming that you enabled the plugin, right? Please, let me know if any of these steps help you!

**Comment by manuelarte** [comment]
Hi lakobs, yes, I enabled the plugin and I also restarted the app, and still got the same error. I am new to GoDoT, so I am still figuring out things. I will come back with the output of the logs

**Comment by manuelarte** [comment]
Hi again @Iakobs . It seems now the autoload error dissaperared, and now I got:

```Error loading configuration for Game Services! Error: 7```

**Comment by Iakobs** [comment]
If I remember correctly that's a login error from Google. Try following the steps in the plugin docs [here](https://github.com/godot-sdk-integrations/godot-play-game-services?tab=readme-ov-file#configuring-the-plugin), or if that's already done, you can check [this](https://github.com/godot-sdk-integrations/godot-play-game-services/tree/main#google-credentials).

Google configuration of Game Services can be a real pain, I tried to simplify the plugin part as much as possible. Let me know how it goes!

**Comment by Iakobs** [comment]
De nada! Pues si la cuenta de Google está suspendida, es probable que sea ese el problema 😳 Espero que te dejen reactivarla fácilmente!

**Comment by manuelarte** [comment]
Hola @lakobs, ya me he recreado la cuenta, he añadido logros (achievements). Tambien he añadido my _Game id_ en el dock `Godot Play Game Services`.

Tambien he puesto este codigo en el ready de mi scene principal:

```gdscript
func _ready() -> void:
	### Authenticate with Google Play Services ###
	if OS.has_feature("android"):
		SignInClient.user_authenticated.connect(func(is_authenticated: bool): # (1)
			if not is_authenticated:
				SignInClient.sign_in()
		)
	###
	...
```

He querido probar solo eso, pero cuando intento exportar el proyecto a android (crear el apk), me encuentro con esto:

![image](https://github.com/user-attachments/assets/d11d1168-f711-4a19-aabd-2106f642f6ad)

(si desactivo el plugin si que puedo exportar)

Se me ha olvidado algo? Importante mencionar que no he creado/puesto nada relacionado con el fingerprint o keystore en el exportador de godot. (No se si me estoy explicando):
![image](https://github.com/user-attachments/assets/a76a1aa2-85a4-4a83-b5b8-aeeb44b6b90e)

**Comment by Iakobs** [comment]
Hola @manuelarte como te he comentado en el repo de la versión de Godot 3.5, he estado fuera durante las vacaciones. Perdona por la demora. En tu edit dices que ya está arreglado el error, ¿Es así? Por lo que veo, parece que faltaba guardar el Game Id, ¿Puede ser que lo pusieras en el editor pero no le dieras al botón de guardar?

Sobre los keystore, en la configuración de export no hacen falta.

**Comment by manuelarte** [comment]
Si, ya esta arreglado, ahora el problema que tengo es que se queda enganchado en la pantalla de logear, aunque le doy a logear, me vuelve a salir lo de logear, pero he abierto otra "issue", asi que esta la podemos dar por cerrada.

**Comment by Iakobs** [comment]
Estupendo!
